inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
  marching_cubes_bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
data:
  input_folder: Datasets/scannet/scans/scene0059_00
  output: output/scannet/scans/scene0059_00