name: nice-slam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.3.29=h06a4308_0
  - certifi=2021.10.8=py37h06a4308_2
  - cffi=1.15.0=py37hd667e15_1
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - embree=2.17.7=ha770c72_1
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.2=py37h295c915_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_14
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.4.3=py37h06a4308_0
  - matplotlib-base=3.4.3=py37hbbc1b5f_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h9c3ff4c_0
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_1
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1n=h166bdaf_0
  - pcre=8.45=h295c915_0
  - pillow=9.0.1=py37h22f2fdc_0
  - pip=22.0.4=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyembree=0.1.6=py37h0da4684_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=61.2.0=py37h89c1867_3
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.1=h4ff8645_0
  - tbb=2021.5.0=h4bd325d_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.12.0=py37_cu113
  - tornado=6.1=py37h27cfd23_0
  - typing_extensions=4.1.1=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - charset-normalizer==2.0.12
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - dask==2022.2.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - filelock==3.6.0
    - fsspec==2022.2.0
    - gdown==4.4.0
    - imageio==2.16.1
    - imath==0.0.1
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - ipykernel==6.10.0
    - ipython==7.32.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.2.0
    - jupyter-core==4.9.2
    - jupyter-packaging==0.12.0
    - jupyter-server==1.16.0
    - jupyterlab==3.3.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.12.0
    - jupyterlab-widgets==1.1.0
    - locket==0.2.1
    - markupsafe==2.1.1
    - mathutils==2.81.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.3.7
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - notebook==6.4.10
    - notebook-shim==0.1.0
    - numpy==1.21.5
    - open3d==0.13.0
    - opencv-python==4.5.5.64
    - openexr==1.3.7
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - partd==1.2.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pygments==2.11.2
    - pyrsistent==0.18.1
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - rtree==0.9.7
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - soupsieve==2.3.1
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomlkit==0.10.1
    - toolz==0.11.2
    - tqdm==4.63.1
    - traitlets==5.1.1
    - trimesh==3.10.7
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - widgetsnbextension==3.6.0
    - zipp==3.7.0