inherit_from: configs/TUM_RGBD/tum.yaml
mapping:
  bound: [[-4.6,2.6],[-3.3,3.2],[-2.0,4.9]]
  marching_cubes_bound: [[-2.6,1.1],[-1.5,1.5],[-0.6,2.4]]
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg1_desk
  output: output/TUM_RGBD/rgbd_dataset_freiburg1_desk
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]